### ISSUE TITLE
Missing Insertion Sort code

### ISSUE THREAD

**Issue by jddeep** [dscgcelt/Competetive-Coding-Repo#1]
Make a PR with C++ code for Insertion Sort.

Try to minimize the time complexity as much as possible.

**Comment by ayanbiswas1101** [comment]
I'll be working on this issue

**Comment by Sayan-dev** [comment]
working on it

**Comment by CapMav** [comment]
Working on it

**Comment by bumblebe-coding** [comment]
I want to work on this

**Comment by jddeep** [comment]
Sure @ayanbiswas1101 You can go ahead with it. :+1:
