### ISSUE TITLE
Functions not given

### ISSUE THREAD

**Issue by bumblebe-coding** [dscgcelt/Competetive-Coding-Repo#13]
In the issues #10, #8 and #9 we are asked to modify a function. But the function is not given with the issue. Would be helpful f you provide the function.

**Comment by Sayan-dev** [comment]
i m working in it

**Comment by Sayan-dev** [comment]
Hope your problem is solved

**Comment by jddeep** [comment]
@bumblebe-coding Have a look at the issues now.

**Comment by bumblebe-coding** [comment]
Yeah....got it

**Comment by bumblebe-coding** [comment]
Should I close the issue now?

**Comment by jddeep** [comment]
Sure @bumblebe-coding If you are satisfied.

**Comment by jddeep** [comment]
@knightcube Please open some more good issues.
